name: BattleBox
version: '1.0'
main: plugins.battlebox.BattleBox
api-version: '1.20'
softdepend: [WorldEdit]

commands:
  loadarena:
    description: Load the default BattleBox arena schematic
    usage: /<command>
    permission: battlebox.admin
    
  arena:
    description: Create and manage BattleBox arenas
    usage: /<command> <create|setcenter|setspawn|setteleport|addkit|save|list|info> [args...]
    permission: battlebox.arena
    
  battlebox:
    description: Main BattleBox game commands
    usage: /<command> <create|join|leave|list|info> [args...]
    permission: battlebox.use

permissions:
  battlebox.use:
    description: Allows player to use basic BattleBox commands
    default: true
    
  battlebox.arena:
    description: Allows player to create and manage arenas
    default: op
    
  battlebox.admin:
    description: Full BattleBox administration access
    default: op
    children:
      - battlebox.use
      - battlebox.arena